package it.polimi.ingsw.Message.ServerMessage;

import it.polimi.ingsw.Controller.MiniController.MiniController;

import java.io.Serializable;

/**
 * This abstract class represents all the messages generated by the Server "directly" during the initialization of a match.
 * Generally all of this kind of messages will result in a new scene (for the GUI) or a new special message (for the CLI) being displayed to the player
 */
public abstract class ServerMessage implements Serializable {
    private static final long serialVersionUID = 1L;
    protected MiniController miniController;

    public abstract MiniController getMiniController();

    public abstract String getMessage();

    /**
     * This method is used to call the correct scene that should be displayed to the player
     */
    public abstract void buildScene();
}
